### ISSUE TITLE
FXCop 1.3 - No FxCop analysis has been performed on this project

### ISSUE THREAD

**Issue by ghost** [SonarQubeCommunity/sonar-fxcop#17]
I have been getting this error for a while now, but I am not sure how to track down the cause, or how to get more info to track it down. If i run the same commands against the same msbuild file, but with a sonarqube project without fxcop rules I do not get this error message. Any help is appreciated. 

```ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: No FxCop analysis has been performed on this project, whereas it contains cs files: Verify that you are using the latest version of the SonarQube Scanner for MSBuild, and if you do, please report a bug. In the short term, you can disable all FxCop rules from your quality profile to get rid of this error.
        at org.sonar.plugins.fxcop.FxCopConfiguration.checkMandatoryProperties(FxCopConfiguration.java:151)
        at org.sonar.plugins.fxcop.FxCopConfiguration.checkProperties(FxCopConfiguration.java:138)
        at org.sonar.plugins.fxcop.FxCopSensor.execute(FxCopSensor.java:69)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
The SonarQube Scanner did not complete successfully
11:56:04.825  Creating a summary markdown file...
11:56:04.825  Post-processing failed. Exit code: 1
```

**Plugins:**
- FXCop: 1.3
- SonarC#: 7.0.1
- SonarQube: 6.7.0.33306 
- SonarScanner: 3.0.3.778 
- MSBuild 15

**Scripts:**
`SonarQube.Scanner.MSBuild.exe begin /key:New-Framework /name:"New Framework" /version:3.2.300 /s:D:\SonarScanner\test.xml`
`MSBuild.exe" D:\Build\NewFramework.MSBuild /p:ProjectRoot=D:\Build;DebugSymbols=true`

**Comment by DanielHWe** [comment]
You missed the command line Parameter for the FxCop Plugin, please see the read me for more Information.

**Comment by ghost** [comment]
Can you point to an MSBuild file or does it have to be a solution?

**Comment by DanielHWe** [comment]
MSBuidl File is not supportet. FxCop Need a Assembly or a FxCop Project (both is supportet by the Plugin) If the Sln file property is provided the solution file is scanned and all assemblies are added to a temporary FxCop Project file

**Comment by ghost** [comment]
Good to know, thanks!
