### ISSUE TITLE
Unable to start SonarQube after this plugin installed

### ISSUE THREAD

**Issue by EbenZhang** [SonarQubeCommunity/sonar-fxcop#4]
Steps 
- Download SonarQube 6.1 (same when using SonarQube 5.6.3)
- Start it using the default configuration(default database)
- Install FxCop 1.0 plugin from the update center
- Restart SonarQube

Error: 

```
2016.11.26 15:29:21 ERROR web[][o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.web.PlatformServletContextListener
java.lang.IllegalStateException: Fail to load plugin FxCop [fxcop]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:73) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:611) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.Platform.start(Platform.java:216) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:190) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:113) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:45) ~[sonar-server-6.1.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_112]
Caused by: java.lang.IllegalStateException: Unable to register extension org.sonar.api.config.PropertyDefinition from plugin 'fxcop'
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:248) ~[sonar-core-6.1.jar:na]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtension(ServerExtensionInstaller.java:110) ~[sonar-server-6.1.jar:na]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:65) ~[sonar-server-6.1.jar:na]
	... 15 common frames omitted
Caused by: org.picocontainer.PicoCompositionException: Duplicate Keys not allowed. Duplicate for 'org.sonar.api.config.PropertyDefinition-sonar.cs.fxcop.timeoutMinutes'
	at org.picocontainer.DefaultPicoContainer.addAdapterInternal(DefaultPicoContainer.java:438) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.addAdapter(DefaultPicoContainer.java:459) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.addComponent(DefaultPicoContainer.java:556) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.access$300(DefaultPicoContainer.java:84) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer$AsPropertiesPicoContainer.addComponent(DefaultPicoContainer.java:1149) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer.addExtension(ComponentContainer.java:246) ~[sonar-core-6.1.jar:na]
	... 17 common frames omitted
2016.11.26 15:29:21 ERROR web[][o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
2016.11.26 15:29:21 ERROR web[][o.a.c.c.StandardContext] Context [] startup failed due to previous errors
```

**Comment by EbenZhang** [comment]
upgrading the c# plugin to 5.5 fixes the problem. But can the log be more informative?
